### ISSUE TITLE
Buy

### ISSUE THREAD

**Issue by floppy1976** [dudanov/iot-uni-dongle#11]
Hello, can you buy the dongle anywhere? It is not possible with Tindi.

**Comment by tomascrespo** [comment]
None? Any place where buying a iot-uni-dongle?

**Comment by dudanov** [comment]
Hello. Check out [this version](https://www.tindie.com/products/smartlightme/wifi-dongle-for-air-conditioners-midea-electrolux) of the dongle.

**Comment by dudanov** [comment]
https://github.com/dudanov/iot-uni-dongle/issues/19#issuecomment-2205122584
